crystal-lang-tools/tree-sitter-crystal

- src/scanner.c
- Replace ASSERT macro with regular `assert()`. `assert` is what the external scanners use in other tree-sitter projects.
- Improve readability of debug logs by adding `[LOG]` to everything that comes from our scanner, instead of using ` ==> `.
- Clean up some redundant log statements that just showed the return value.
- Move the pre- and post-scan logging into a separate method.
> Scanner usability updates

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
- test/corpus/todo.txt
- test/stdlib_coverage_expected_to_fail.txt
Closes #7 
In the stdlib, this is a node called ReadInstanceVar - I don't think that needs to be done here though.
5 more stdlib files parse without errors
> Allow instance vars to be the method of a call

- grammar.js
- src/grammar.json
- src/scanner.c
https://github.com/crystal-lang-tools/tree-sitter-crystal/pull/12 solved the problem of `'#'` being parsed as a comment, but I want to suggest a different way to handle this.
I believe this is a [token conflict](https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens). The `comment` rule is in `extras`, so it can match almost anywhere. And `comment` took precedence because the regex it's using, `/#.*/`, generates a longer match than `/[^\\]/`.
Using `_char_comment` in the external scanner only overrides the precedence for `#`. Using `prec(1, ...)` will also handle any future token conflicts if new rules get added to `extras`.
> Set token precedence for char rule

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
- test/corpus/statements.txt
- test/corpus/todo.txt
- test/stdlib_coverage.cr
- test/stdlib_coverage_expected_to_fail.txt
Closes #30, #28
- Adds support for global calls (`::raise "message"`)
- Allow symbols to end with `=` (still more todo for this though)
- Allow comma-separated and parenthesized break / next / return values
- Make condition in case statement optional
- Enums can be private
- Print whether a stdlib file contains macros when doing coverage (useful for finding non-macro parsing errors)
24 more stdlib files can be parsed without errors.
> Add more to `todo.txt` and fix some parsing errors

- src/scanner.c
For some reason calling lexer->log(...) breaks WASM builds, so it should be disabled temporarily. It can be re-enabled locally for debugging as necessary.
> Don't use lexer->log(...) by default

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
This was a weird structure anyways, and it unintentionally supported illegal syntax like `a.[1] do end`. Now the `_dot_call` rule makes more sense, and assignment with `a.[arg]` syntax is fully supported.
This change shrinks the parser by ~540 states, a 3% decrease.
> Move dot index calls to a separate rule

- grammar.js
- src/grammar.json
- test/corpus/expressions.txt
`parser.c` is 2.5 MB smaller, and `tree-sitter generate` runs 2 seconds faster on my machine
> Misc performance improvements

- src/scanner.c
- test/corpus/expressions.txt
Using the `tree-sitter fuzz` command triggered an assertion failure with this sequence:
```
../
```
The fuzz command gives some other warnings, but they all seem related to whether leading whitespace is counted as part of a token or not. I think this was the only serious failure.
> Fix an assertion failure when scanning /

- grammar.js
- queries/nvim/folds.scm
- src/grammar.json
- src/node-types.json
- test/corpus/errors.txt
- test/corpus/expressions.txt
- test/corpus/literals.txt
- test/corpus/statements.txt
- test/corpus/todo.txt
- test/corpus/types.txt
- Alias `op_call` nodes to `call`, and make their fields the same.
In other words, these have identical parse trees now: 
``` crystal
1 + 2 + 3
1.+(2).+(3)
```
- Alias `multi_assign` to `assign`. They share `lhs:` and `rhs:` fields, I don't see a reason to keep separate node types.
- Rename `rescue_block` to `rescue` and `begin_block` to `begin`, the `_block suffix was redundant
- Always use `cond` instead of `condition` for field names
- Use `operator` for a few more operators
> Node consistency fixes

- .github/workflows/compile_check.yml
- src/scanner.c
Add a new check to verify the grammar builds without warnings on Windows, macOS, and Ubuntu.
Will run if any of the C files _except_ `src/parser.c` is modified. (I assume tree-sitter will always output safe, standards-compliant parser code.)
> Check for grammar compile warnings

- src/scanner.c
I found the CI failure in https://github.com/nvim-treesitter/nvim-treesitter/pull/7481 was caused by the static assert statement. Turns out, MSVC only supports static assertions when `/std:c11` or later is passed explicitly.
> Only use static_assert on C11 or later

- grammar.js
- queries/nvim/highlights.scm
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
- test/corpus/types.txt
Make `underscore` a valid node on the left hand side of assignments, and other places
> Use `underscore` in more places

- grammar.js
- src/grammar.json
- src/scanner.c
- test/corpus/literals.txt
- test/corpus/todo.txt
We need to use lookahead to determine if a symbol ends with `=` or `!`.
I was hoping to use an external token just for the last character, but `token` cannot contain externals :confused:
> Move plain symbols to the external scanner

- grammar.js
- src/grammar.json
Just a small optimization that shrinks the parser size.
> Split macro_def into two rules

- queries/nvim/folds.scm
Now this can be folded (I love how easy this is):
``` crystal
a = [
1,
2,
3
]
```
> Add folds for multi-line data structures

- .ameba.yml
- src/scanner.c
- test/highlight/tuples.cr
- test/highlight/types.cr
- tree-sitter.json
For several tokens, `advance(skip=true)` could be called after `mark_end`. This sets the start of the token past the end, so it was returned as zero-width. Apparently syntax highlighting doesn't work well with zero-width tokens.
I'm also adding the first set of highlighting tests, using the neovim queries for now.
> Scanner skip changes

- queries/nvim/aerial.scm
A plugin to provide an outline view of current buffer. https://github.com/stevearc/aerial.nvim
I saw some queries in their repo for constants, however they aren't visible with the default aerial configuration, but I added them anyway.
> Add queries for nvim aerial plugin.

- Makefile
Not sure of a better way to handle rebuilding these when the Crystal version changes ¯\\\_(ツ)\_/¯
> Remove test binaries with `make clean`

- queries/nvim/context.scm
Meant to be used with https://github.com/nvim-treesitter/nvim-treesitter-context
> Implement tree-sitter context queries.

- test/corpus/todo.txt
I ran the parser on some other crystal codebases (the shards package manager, and some of the popular web frameworks). Found a few more small issues.
> Add some more currently-failing examples

- grammar.js
- src/grammar.json
- src/node-types.json
- src/scanner.c
- test/corpus/expressions.txt
- test/corpus/todo.txt
After working around https://github.com/tree-sitter/tree-sitter/issues/4091, this means the `tree-sitter fuzz` command is useful now!
> Move ` \s:\s` token to external scanner

- src/scanner.c
- test/corpus/errors.txt
Address an assertion failure triggered by
```
Foo { a: 1 }
```
> Fix named tuple assertion failure

- grammar.js
- queries/nvim/highlights.scm
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
- test/corpus/literals.txt
- test/util.cr
The grammar has several types of escape sequence nodes:
- `char_escape_sequence` (only for chars)
- `string_escape_sequence` (everywhere else, not only for strings)
- `ignored_backslash` (used for "identity" escape sequences)
This PR renames all the above to `escape_sequence`. I've adjusted the highlighting as well, so `escape_sequence` is always highlighted in a color that contrasts with the surrounding content.
There are also line continuation backslashes, which are currently hidden nodes without any highlighting. These are unchanged. My intent here is that a line continuation looks different because it's not escaping a newline, it's obscuring a newline.
Highlighting improvements:
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details>
> Use `escape_sequence` for all escape types

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/macros.txt
- test/corpus/statements.txt
- test/corpus/todo.txt
- test/crystal_parse_stdlib_fail.txt
- test/stdlib_coverage_expected_to_fail.txt
This adds support for `"#{a if b}"`, `{{a unless b}}`, etc.
Also supports syntax that no one should use but is technically allowed, like
```crystal
def foo
a = "#{return 7}"
end
foo #=> 7
```
I don't love how much this blows up the state count, but it seems unavoidable.
> Support modifier and control statements in interpolations
